version: '3.1'

services:
  mariadb-galera:
    container_name: "mariadb-galera"
    image: 'bitnami/mariadb-galera:10.9'
    restart: always
    environment:
      - MARIADB_GALERA_CLUSTER_NAME="galera_node"
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://103.174.50.226,103.174.50.227,103.174.50.210
      - MARIADB_ROOT_PASSWORD=aamarpay@2020
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=aamarpay@2020
      - MARIADB_GALERA_NODE_ADDRESS=103.174.50.210
      - BITNAMI_DEBUG=true
      - MARIADB_EXTRA_FLAGS=--wsrep_node_name="node210" --wsrep_provider_options=ist.recv_addr=103.174.50.210:4568;ist.recv_bind=0.0.0.0:4568 --wsrep_node_incoming_address=103.174.50.210 --wsrep_sst_receive_address=103.174.50.210
    network_mode: host
    hostname: galera3.aamarpay.com
    volumes:
      - /home/mariadb_storage:/bitnami/mariadb

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin
    restart: always
    network_mode: host
    environment:
      - PMA_ARBITRARY=1